(define s (make-socket))
(socket-bind s "0.0.0.0" 1234)
(socket-listen s (lambda (c)
  (socket-write c "abc" (lambda(cc) cc))))
;  (remove-socket c)
;  (remove-socket s)))
(define c (make-socket))
(socket-connect c "0.0.0.0" 1234 (lambda (cc)
  (socket-read cc (lambda (d) (display d)
  (remove-socket c)
  (remove-socket s)))))
