(define s (make-socket))
(socket-bind s "0.0.0.0" 1234)
(socket-listen s (lambda (c)
  (display c)
  (remove-socket c)
  (remove-socket s)))
(define c (make-socket))
(socket-connect c "0.0.0.0" 1234 (lambda (cc)
  (display cc)
  (remove-socket c)))
